CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app123';

GRANT ALL PRIVILEGES ON app.* TO 'app'@'%' IDENTIFIED BY 'app123';

CREATE DATABASE IF NOT EXISTS app;
ALTER DATABASE app DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;